[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "msclub"
authors = [{name = "LUX club", email = "mrchanmp@gmx.com"}]
dynamic = ["version", "description"]
